### ISSUE TITLE
Create a Script for Generating new Blog Posts

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/blog#4]
Since there's a bit of details needed in the yaml formatting at the top, we should make a script to prompt the user for everything they need and generate the properly formatted `.md` file for them to work with.

This would be a great Hackathon issue for someone to deal with

**Comment by RamZallan** [comment]
Below is the YAML front matter from the template in the repo, for reference.
```yaml
---
layout: post
title: Template
date: 2017-10-20
categories:
  - Template
description: Template of Templates
image: https://unsplash.it/2000/1200?image=1003
image-sm: https://unsplash.it/500/300?image=1003
author: Devin Matte
author-image: https://avatars3.githubusercontent.com/u/9310513
author-bio: Second Year Student
author-email: devin@devinmatte.com
author-social:
  github: https://github.com/devinmatte
  linkedin: https://www.linkedin.com/in/devin-m-5556a386/
---
```
